name: hello
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"

  git-log:
    runs-on: ubuntu-latest
    steps:
      - run: |
        git log -1
        tree -a .
